// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnotmdUY2PsiXztoJEJu2AaeeSEp9qHQY',
    appId: '1:403402572122:web:19668f164aa7565b9f7363',
    messagingSenderId: '403402572122',
    projectId: 'gp02-6e08a',
    authDomain: 'gp02-6e08a.firebaseapp.com',
    storageBucket: 'gp02-6e08a.firebasestorage.app',
    measurementId: 'G-L0B1G1ECCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoK2QOe9yO1KI1zAwkeCZqmdKh0IVMtCM',
    appId: '1:403402572122:android:c3ec6e81fe5014879f7363',
    messagingSenderId: '403402572122',
    projectId: 'gp02-6e08a',
    storageBucket: 'gp02-6e08a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3RlZX61Rj3nSJLMyBc57f5gbj1r_cH1U',
    appId: '1:403402572122:ios:0b0e7223b74c80ac9f7363',
    messagingSenderId: '403402572122',
    projectId: 'gp02-6e08a',
    storageBucket: 'gp02-6e08a.firebasestorage.app',
    iosBundleId: 'com.example.qusai',
  );
}
